object Libraries {
    const val classpathGradle = "com.android.tools.build:gradle:${Versions.gradle}"
    const val classpathKotlinGradle = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    const val classpathNavigation = "androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.nav}"
    const val classpathNexus = "io.github.gradle-nexus:publish-plugin:${Versions.nexus}"
    const val classpathDokka = "org.jetbrains.dokka:dokka-gradle-plugin:${Versions.dokka}"

    const val stdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit2}"
    const val retrofitConverterGson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit2}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp3}"
    const val okhttpLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp3}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutinesCore}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutinesAndroid}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val lifecycleLivedata = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycle}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    const val lifecycleJava8 = "androidx.lifecycle:lifecycle-common-java8:${Versions.lifecycle}"
    const val lifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycleExtensions}"
    const val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.nav}"
    const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.nav}"
    const val activity = "androidx.activity:activity-ktx:${Versions.activity}"
    const val legacySupportV4 = "androidx.legacy:legacy-support-v4:${Versions.legacySupportV4}"
    const val shimmer = "com.facebook.shimmer:shimmer:${Versions.shimmer}"
    const val camera2 = "androidx.camera:camera-camera2:${Versions.camerax}"
    const val cameraLifecycle = "androidx.camera:camera-lifecycle:${Versions.camerax}"
    const val cameraView = "androidx.camera:camera-view:${Versions.cameraView}"
    const val googleRecognition = "com.google.android.gms:play-services-mlkit-text-recognition:${Versions.googleRecognition}"
    const val googleWallet = "com.google.android.gms:play-services-wallet:${Versions.googleWallet}"
    const val cardinalMobileSDK = "org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:${Versions.cardinalMobileSDK}"

    const val junit = "junit:junit:${Versions.junit}"
    const val mockitoKotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Versions.mockitoKotlin}"
    const val mockitoInline = "org.mockito:mockito-inline:${Versions.mockitoInline}"
    const val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.coroutinesTest}"
    const val okhttpMockWebserver = "com.squareup.okhttp3:mockwebserver:${Versions.okhttp3}"
    const val androidxExtJunit = "androidx.test.ext:junit:${Versions.junitTest}"
    const val androidxEspressoCore = "androidx.test.espresso:espresso-core:${Versions.espressoCore}"
}