object Versions {
    const val gradle = "7.0.3"
    const val nexus = "1.1.0"
    const val dokka = "1.5.31"
    const val kotlin = "1.5.31"
    const val appCompat = "1.3.1"
    const val coreKtx = "1.7.0"
    const val lifecycle = "2.4.0"
    const val lifecycleExtensions = "2.2.0"
    const val material = "1.5.0-beta01"
    const val constraintLayout = "2.1.1"
    const val coroutinesAndroid = "1.5.1"
    const val coroutinesCore = "1.5.0"
    const val activity = "1.4.0"
    const val nav ="2.3.5"
    const val retrofit2 = "2.9.0"
    const val okhttp3 = "4.9.2"
    const val gson = "2.8.9"
    const val camerax = "1.0.2"
    const val cameraView = "1.0.0-alpha30"
    const val legacySupportV4 = "1.0.0"
    const val shimmer = "0.5.0"
    const val googleRecognition = "17.0.0"
    const val googleWallet = "18.1.3"
    const val cardinalMobileSDK = "2.2.6-1"

    const val junit = "4.13.2"
    const val junitTest = "1.1.3"
    const val espressoCore = "3.4.0"
    const val mockitoKotlin = "2.2.0"
    const val mockitoInline = "2.8.47"
    const val coroutinesTest = "1.4.2"
}